// Code generated by sqlc-gen-sqlx v0.1.4. DO NOT EDIT.
// sqlc version: v1.30.0

#![allow(dead_code, reason = "generated queries may expose items a caller does not use")]

const GET_AUTHOR: &str = "SELECT id, name, bio FROM authors WHERE id = $1";
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct GetAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
const LIST_AUTHORS: &str = "SELECT id, name, bio FROM authors ORDER BY name";
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ListAuthorsRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
#[derive(Debug, Clone)]
pub struct CreateAuthorParams {
    pub name: String,
    pub bio: Option<String>,
}
const CREATE_AUTHOR: &str = "INSERT INTO authors (name, bio) VALUES ($1, $2) RETURNING id, name, bio";
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct CreateAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
const DELETE_AUTHOR: &str = "DELETE FROM authors WHERE id = $1";
const DELETE_AUTHOR_ROWS: &str = "DELETE FROM authors WHERE id = $1";
pub trait AsExecutor {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres>;
}
impl AsExecutor for sqlx::PgPool {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        &*self
    }
}
impl AsExecutor for &sqlx::PgPool {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        *self
    }
}
impl AsExecutor for sqlx::PgConnection {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        &mut *self
    }
}
impl AsExecutor for sqlx::Transaction<'_, sqlx::Postgres> {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        &mut **self
    }
}
impl AsExecutor for sqlx::pool::PoolConnection<sqlx::Postgres> {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        &mut **self
    }
}
impl<T: AsExecutor + ?Sized> AsExecutor for &mut T {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        (**self).as_executor()
    }
}
#[derive(Copy, Clone)]
pub struct Queries<E> {
    db: E,
}
impl<E> Queries<E> {
    pub fn new(db: E) -> Self {
        Self { db }
    }
    pub fn into_inner(self) -> E {
        self.db
    }
}
impl<E: AsExecutor> Queries<E> {
    pub async fn get_author(&mut self, id: i64) -> Result<GetAuthorRow, sqlx::Error> {
        sqlx::query_as::<_, GetAuthorRow>(GET_AUTHOR)
            .bind(id)
            .fetch_one(self.db.as_executor())
            .await
    }
    pub async fn list_authors(&mut self) -> Result<Vec<ListAuthorsRow>, sqlx::Error> {
        sqlx::query_as::<_, ListAuthorsRow>(LIST_AUTHORS)
            .fetch_all(self.db.as_executor())
            .await
    }
    pub async fn create_author(
        &mut self,
        arg: CreateAuthorParams,
    ) -> Result<CreateAuthorRow, sqlx::Error> {
        sqlx::query_as::<_, CreateAuthorRow>(CREATE_AUTHOR)
            .bind(arg.name)
            .bind(arg.bio)
            .fetch_one(self.db.as_executor())
            .await
    }
    pub async fn delete_author(&mut self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(DELETE_AUTHOR).bind(id).execute(self.db.as_executor()).await?;
        Ok(())
    }
    pub async fn delete_author_rows(&mut self, id: i64) -> Result<u64, sqlx::Error> {
        let result = sqlx::query(DELETE_AUTHOR_ROWS)
            .bind(id)
            .execute(self.db.as_executor())
            .await?;
        Ok(result.rows_affected())
    }
}
