// Code generated by sqlc-gen-sqlx v0.1.0. DO NOT EDIT.
// sqlc version: v1.30.0

#![allow(
    dead_code,
    reason = "generated queries may expose items a caller does not use"
)]

const GET_AUTHOR: &str = "SELECT id, name, bio FROM authors WHERE id = $1";
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct GetAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
const LIST_AUTHORS: &str = "SELECT id, name, bio FROM authors ORDER BY name";
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ListAuthorsRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
#[derive(Debug, Clone)]
pub struct CreateAuthorParams {
    pub name: String,
    pub bio: Option<String>,
}
const CREATE_AUTHOR: &str =
    "INSERT INTO authors (name, bio) VALUES ($1, $2) RETURNING id, name, bio";
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct CreateAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
const DELETE_AUTHOR: &str = "DELETE FROM authors WHERE id = $1";
const DELETE_AUTHOR_ROWS: &str = "DELETE FROM authors WHERE id = $1";
pub struct Queries<E> {
    db: E,
}
impl<E> Queries<E> {
    pub fn new(db: E) -> Self {
        Self { db }
    }
}
impl<E> Queries<E>
where
    for<'c> &'c mut E: sqlx::Executor<'c, Database = sqlx::Postgres>,
{
    pub async fn get_author(&mut self, id: i64) -> Result<GetAuthorRow, sqlx::Error> {
        sqlx::query_as::<_, GetAuthorRow>(GET_AUTHOR)
            .bind(id)
            .fetch_one(&mut self.db)
            .await
    }
    pub async fn list_authors(&mut self) -> Result<Vec<ListAuthorsRow>, sqlx::Error> {
        sqlx::query_as::<_, ListAuthorsRow>(LIST_AUTHORS)
            .fetch_all(&mut self.db)
            .await
    }
    pub async fn create_author(
        &mut self,
        arg: CreateAuthorParams,
    ) -> Result<CreateAuthorRow, sqlx::Error> {
        sqlx::query_as::<_, CreateAuthorRow>(CREATE_AUTHOR)
            .bind(arg.name)
            .bind(arg.bio)
            .fetch_one(&mut self.db)
            .await
    }
    pub async fn delete_author(&mut self, id: i64) -> Result<(), sqlx::Error> {
        sqlx::query(DELETE_AUTHOR)
            .bind(id)
            .execute(&mut self.db)
            .await?;
        Ok(())
    }
    pub async fn delete_author_rows(&mut self, id: i64) -> Result<u64, sqlx::Error> {
        let result = sqlx::query(DELETE_AUTHOR_ROWS)
            .bind(id)
            .execute(&mut self.db)
            .await?;
        Ok(result.rows_affected())
    }
}
