// Code generated by sqlc-gen-sqlx. DO NOT EDIT.

#![allow(
    dead_code,
    reason = "generated queries may expose items a caller does not use"
)]

const GET_EVENT: &str = "SELECT id, name, flags, event_window FROM events WHERE id = $1";

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct GetEventRow {
    pub id: i64,
    pub name: String,
    pub flags: bit_vec::BitVec,
    pub event_window: sqlx::postgres::types::PgRange<chrono::DateTime<chrono::Utc>>,
}

const LIST_EVENTS: &str = "SELECT id, name, flags, event_window FROM events";

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ListEventsRow {
    pub id: i64,
    pub name: String,
    pub flags: bit_vec::BitVec,
    pub event_window: sqlx::postgres::types::PgRange<chrono::DateTime<chrono::Utc>>,
}

pub struct Queries<E> {
    db: E,
}

impl<E> Queries<E> {
    pub fn new(db: E) -> Self {
        Self { db }
    }
}

impl<E> Queries<E>
where
    for<'c> &'c mut E: sqlx::Executor<'c, Database = sqlx::Postgres>,
{
    pub async fn get_event(&mut self, id: i64) -> Result<GetEventRow, sqlx::Error> {
        sqlx::query_as::<_, GetEventRow>(GET_EVENT)
            .bind(id)
            .fetch_one(&mut self.db)
            .await
    }

    pub async fn list_events(&mut self) -> Result<Vec<ListEventsRow>, sqlx::Error> {
        sqlx::query_as::<_, ListEventsRow>(LIST_EVENTS)
            .fetch_all(&mut self.db)
            .await
    }
}
