// Code generated by sqlc-gen-sqlx v0.1.7. DO NOT EDIT.
// sqlc version: v1.30.0

#![allow(
    dead_code,
    reason = "generated queries may expose items a caller does not use"
)]

pub trait AsExecutor {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres>;
}
impl AsExecutor for sqlx::PgPool {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        &*self
    }
}
impl AsExecutor for &sqlx::PgPool {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        *self
    }
}
impl AsExecutor for sqlx::PgConnection {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        &mut *self
    }
}
impl AsExecutor for sqlx::Transaction<'_, sqlx::Postgres> {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        &mut **self
    }
}
impl AsExecutor for sqlx::pool::PoolConnection<sqlx::Postgres> {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        &mut **self
    }
}
impl<T: AsExecutor + ?Sized> AsExecutor for &mut T {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        (**self).as_executor()
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, sqlx::Type)]
#[sqlx(type_name = "status")]
pub enum Status {
    #[sqlx(rename = "active")]
    Active,
    #[sqlx(rename = "inactive")]
    Inactive,
    #[sqlx(rename = "pending")]
    Pending,
}
const GET_USER: &str = "SELECT id, name, status FROM users WHERE id = $1";
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct GetUserRow {
    pub id: i64,
    pub name: String,
    pub status: Status,
}
pub async fn get_user<E: AsExecutor>(mut db: E, id: i64) -> Result<GetUserRow, sqlx::Error> {
    sqlx::query_as::<_, GetUserRow>(GET_USER)
        .bind(id)
        .fetch_one(db.as_executor())
        .await
}
const LIST_USERS_BY_STATUS: &str = "SELECT id, name, status FROM users WHERE status = $1";
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ListUsersByStatusRow {
    pub id: i64,
    pub name: String,
    pub status: Status,
}
pub async fn list_users_by_status<E: AsExecutor>(
    mut db: E,
    status: Status,
) -> Result<Vec<ListUsersByStatusRow>, sqlx::Error> {
    sqlx::query_as::<_, ListUsersByStatusRow>(LIST_USERS_BY_STATUS)
        .bind(status)
        .fetch_all(db.as_executor())
        .await
}
#[derive(Debug, Clone)]
pub struct CreateUserParams {
    pub name: String,
    pub status: Status,
}
const CREATE_USER: &str = "INSERT INTO users (name, status) VALUES ($1, $2)";
pub async fn create_user<E: AsExecutor>(
    mut db: E,
    arg: CreateUserParams,
) -> Result<(), sqlx::Error> {
    sqlx::query(CREATE_USER)
        .bind(arg.name)
        .bind(arg.status)
        .execute(db.as_executor())
        .await?;
    Ok(())
}
