// Code generated by sqlc-gen-sqlx. DO NOT EDIT.

#![allow(
    dead_code,
    reason = "generated queries may expose items a caller does not use"
)]

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, sqlx::Type)]
#[sqlx(type_name = "status")]
pub enum Status {
    #[sqlx(rename = "active")]
    Active,
    #[sqlx(rename = "inactive")]
    Inactive,
    #[sqlx(rename = "pending")]
    Pending,
}

const GET_USER: &str = "SELECT id, name, status FROM users WHERE id = $1";

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct GetUserRow {
    pub id: i64,
    pub name: String,
    pub status: Status,
}

const LIST_USERS_BY_STATUS: &str = "SELECT id, name, status FROM users WHERE status = $1";

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct ListUsersByStatusRow {
    pub id: i64,
    pub name: String,
    pub status: Status,
}

const CREATE_USER: &str = "INSERT INTO users (name, status) VALUES ($1, $2)";

pub struct Queries<E> {
    db: E,
}

impl<E> Queries<E> {
    pub fn new(db: E) -> Self {
        Self { db }
    }
}

impl<E> Queries<E>
where
    for<'c> &'c mut E: sqlx::Executor<'c, Database = sqlx::Postgres>,
{
    pub async fn get_user(&mut self, id: i64) -> Result<GetUserRow, sqlx::Error> {
        sqlx::query_as::<_, GetUserRow>(GET_USER)
            .bind(id)
            .fetch_one(&mut self.db)
            .await
    }

    pub async fn list_users_by_status(
        &mut self,
        status: Status,
    ) -> Result<Vec<ListUsersByStatusRow>, sqlx::Error> {
        sqlx::query_as::<_, ListUsersByStatusRow>(LIST_USERS_BY_STATUS)
            .bind(status)
            .fetch_all(&mut self.db)
            .await
    }

    pub async fn create_user(&mut self, name: String, status: Status) -> Result<(), sqlx::Error> {
        sqlx::query(CREATE_USER)
            .bind(name)
            .bind(status)
            .execute(&mut self.db)
            .await?;
        Ok(())
    }
}
