// Code generated by sqlc-gen-sqlx v0.1.5. DO NOT EDIT.
// sqlc version: v1.30.0

#![allow(
    dead_code,
    reason = "generated queries may expose items a caller does not use"
)]

const BATCH_GET_AUTHOR: &str = "SELECT id, name, bio FROM authors WHERE id = $1";
#[derive(Debug, Clone, sqlx::FromRow)]
pub struct BatchGetAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}
const BATCH_DELETE_AUTHOR: &str = "DELETE FROM authors WHERE id = $1";
pub trait AsExecutor {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres>;
}
impl AsExecutor for sqlx::PgPool {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        &*self
    }
}
impl AsExecutor for &sqlx::PgPool {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        *self
    }
}
impl AsExecutor for sqlx::PgConnection {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        &mut *self
    }
}
impl AsExecutor for sqlx::Transaction<'_, sqlx::Postgres> {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        &mut **self
    }
}
impl AsExecutor for sqlx::pool::PoolConnection<sqlx::Postgres> {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        &mut **self
    }
}
impl<T: AsExecutor + ?Sized> AsExecutor for &mut T {
    fn as_executor(&mut self) -> impl sqlx::Executor<'_, Database = sqlx::Postgres> {
        (**self).as_executor()
    }
}
#[derive(Copy, Clone)]
pub struct Queries<E> {
    db: E,
}
impl<E> Queries<E> {
    pub fn new(db: E) -> Self {
        Self { db }
    }
    pub fn into_inner(self) -> E {
        self.db
    }
}
impl<E: AsExecutor> Queries<E> {
    pub fn batch_get_author<'a, I>(
        &'a mut self,
        items: I,
    ) -> impl futures_core::stream::Stream<Item = Result<BatchGetAuthorRow, sqlx::Error>> + 'a
    where
        I: IntoIterator<Item = i64> + 'a,
        I::IntoIter: 'a,
        E: 'a,
    {
        futures_util::stream::try_unfold(
            (&mut self.db, items.into_iter()),
            |(db, mut items)| async move {
                let Some(item) = items.next() else {
                    return Ok(None);
                };
                let row = sqlx::query_as::<_, BatchGetAuthorRow>(BATCH_GET_AUTHOR)
                    .bind(item)
                    .fetch_one(db.as_executor())
                    .await?;
                Ok(Some((row, (db, items))))
            },
        )
    }
    pub fn batch_delete_author<'a, I>(
        &'a mut self,
        items: I,
    ) -> impl futures_core::stream::Stream<Item = Result<(), sqlx::Error>> + 'a
    where
        I: IntoIterator<Item = i64> + 'a,
        I::IntoIter: 'a,
        E: 'a,
    {
        futures_util::stream::try_unfold(
            (&mut self.db, items.into_iter()),
            |(db, mut items)| async move {
                let Some(item) = items.next() else {
                    return Ok(None);
                };
                sqlx::query(BATCH_DELETE_AUTHOR)
                    .bind(item)
                    .execute(db.as_executor())
                    .await?;
                Ok(Some(((), (db, items))))
            },
        )
    }
}
