// Code generated by sqlc-gen-sqlx. DO NOT EDIT.

#![allow(
    dead_code,
    reason = "generated queries may expose items a caller does not use"
)]

const BATCH_GET_AUTHOR: &str = "SELECT id, name, bio FROM authors WHERE id = $1";

#[derive(Debug, Clone, sqlx::FromRow)]
pub struct BatchGetAuthorRow {
    pub id: i64,
    pub name: String,
    pub bio: Option<String>,
}

const BATCH_DELETE_AUTHOR: &str = "DELETE FROM authors WHERE id = $1";

pub struct Queries<E> {
    db: E,
}

impl<E> Queries<E> {
    pub fn new(db: E) -> Self {
        Self { db }
    }
}

impl<E> Queries<E>
where
    for<'c> &'c mut E: sqlx::Executor<'c, Database = sqlx::Postgres>,
{
    pub async fn batch_get_author(
        &mut self,
        items: Vec<i64>,
    ) -> Result<Vec<BatchGetAuthorRow>, sqlx::Error> {
        let mut results = Vec::with_capacity(items.len());
        for item in items {
            let row = sqlx::query_as::<_, BatchGetAuthorRow>(BATCH_GET_AUTHOR)
                .bind(item)
                .fetch_one(&mut self.db)
                .await?;
            results.push(row);
        }
        Ok(results)
    }

    pub async fn batch_delete_author(&mut self, items: Vec<i64>) -> Result<(), sqlx::Error> {
        for item in items {
            sqlx::query(BATCH_DELETE_AUTHOR)
                .bind(item)
                .execute(&mut self.db)
                .await?;
        }
        Ok(())
    }
}
