// @generated by buffa-codegen. DO NOT EDIT.

include!("plugin.codegen.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("plugin.codegen.__view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::FileView;
#[doc(inline)]
pub use self::__buffa::view::FileOwnedView;
#[doc(inline)]
pub use self::__buffa::view::SettingsView;
#[doc(inline)]
pub use self::__buffa::view::SettingsOwnedView;
#[doc(inline)]
pub use self::__buffa::view::CodegenView;
#[doc(inline)]
pub use self::__buffa::view::CodegenOwnedView;
#[doc(inline)]
pub use self::__buffa::view::CatalogView;
#[doc(inline)]
pub use self::__buffa::view::CatalogOwnedView;
#[doc(inline)]
pub use self::__buffa::view::SchemaView;
#[doc(inline)]
pub use self::__buffa::view::SchemaOwnedView;
#[doc(inline)]
pub use self::__buffa::view::CompositeTypeView;
#[doc(inline)]
pub use self::__buffa::view::CompositeTypeOwnedView;
#[doc(inline)]
pub use self::__buffa::view::EnumView;
#[doc(inline)]
pub use self::__buffa::view::EnumOwnedView;
#[doc(inline)]
pub use self::__buffa::view::TableView;
#[doc(inline)]
pub use self::__buffa::view::TableOwnedView;
#[doc(inline)]
pub use self::__buffa::view::IdentifierView;
#[doc(inline)]
pub use self::__buffa::view::IdentifierOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ColumnView;
#[doc(inline)]
pub use self::__buffa::view::ColumnOwnedView;
#[doc(inline)]
pub use self::__buffa::view::QueryView;
#[doc(inline)]
pub use self::__buffa::view::QueryOwnedView;
#[doc(inline)]
pub use self::__buffa::view::ParameterView;
#[doc(inline)]
pub use self::__buffa::view::ParameterOwnedView;
#[doc(inline)]
pub use self::__buffa::view::GenerateRequestView;
#[doc(inline)]
pub use self::__buffa::view::GenerateRequestOwnedView;
#[doc(inline)]
pub use self::__buffa::view::GenerateResponseView;
#[doc(inline)]
pub use self::__buffa::view::GenerateResponseOwnedView;
